#' Sets default plotting for history log
#'
#' This function sets up the default plotting method
#' for outputs from deconvolve function
#'
#' @param x history object as generated by history function
#' @param ... other options passed to plot
#' @return plot
#' @import pryr
#' @method plot decon
#' @importFrom graphics legend lines par plot
#'
#' @export

plot.history <- function (x, ...) {

  

}

