#' Sets default plotting for timeline
#'
#' This function sets up the default plotting method
#' for outputs from timeline function
#'
#' @param x timeline object as generated by timeline function
#' @param records list the number of records you'd like to show
#' @param ... other options passed to plot
#' @return plot
#' @method plot timeline
#' @importFrom igraph graph_from_literal
#' @importFrom graphics plot
#'
#' @export

plot.timeline <- function (x, records = 6, ...) {

  top <- x[1:records,]
  
  vertex_names <- paste(top$record_id, collapse = '-')
  graph_call <- call("graph_from_literal", parse(text = vertex_names)[[1]])
  graph <- eval(graph_call)
  plot(graph, vertex.size = 30, vertex.color = 'lightblue')
  
  # library(shiny)
  # library(miniUI)
  # 
  # ui <- miniPage(
  #   gadgetTitleBar('TGA deconvolution',
  #                  right = miniTitleBarButton('done', 'Done', primary = TRUE)
  #   ),
  #   
  #   miniTabstripPanel(
  #     i
  # )
  # 
  # server <- function (input, output, session) {
  #   
  #   output$plot <- reactivePlot(function() {
  #     
  #     data = 
  #     
  #   })
  #   
  #   ### DONE button ###
  #   observeEvent(input$done, {
  #     returnValue <-
  #       stopApp(returnValue)
  #   })
  #   
  # }
  # 
  # runGadget(ui, server, viewer = dialogViewer('deconvolveGadgetFunc'))
  # 

}

