#' Sets default print method for history logs
#'
#' This function sets up the default print method
#' for outputs of the history function
#'
#' @param x history object as generated by history function
#' @param ... other options passed to print
#' @return print history
#' @method print history
#'
#' @export

print.history <- function (x, ...) {

  x_rev <- x[seq(dim(x)[1],1),]

  for (i in 1:length(x_rev)) {
    
    x_rev$message <- gsub("\\n+", ": ", x_rev$message)
    cat(paste0('\t() Record ID: ', x_rev$record_id, '\n',
               '\t | Author: ', x_rev$author, '\n',
               '\t | Date & Time: ', x_rev$when, '\n',
               '\t | Message: ', x_rev$message, '\n',
               '\t | \n',
               '\t | \n',
               '\t | \n'))
    
  }
  
}
