#' Sets default print method for timeline
#'
#' This function sets up the default print method
#' for outputs of the timeline function
#'
#' @param x timeline object as generated by timeline function
#' @param ... other options passed to print
#' @return print timeline
#' @method print timeline
#'
#' @export

print.timeline <- function (x, ...) {

  x_rev <- x[seq(dim(x)[1],1),]

  output <- for (i in 1:length(x_rev)) {
    
    x_rev$message <- gsub("\\n+", ": ", x_rev$message)
    cat(paste0('\t() Record No: ', x_rev$record_id, '\n',
               '\t | Author: ', x_rev$author, '\n',
               '\t | Date & Time: ', x_rev$when, '\n',
               '\t | Message: ', x_rev$message, '\n',
               '\t | sha key: ', x_rev$sha, '\n',
               '\t | \n',
               '\t | \n',
               '\t | \n'))
    
  }
  
  print(output)
  invisible(x)
  
}
