#' Sets default print method for timeline
#'
#' This function sets up the default print method
#' for outputs of the timeline function
#'
#' @param x timeline object as generated by timeline function
#' @param ... other options passed to print
#' @return print timeline
#' @method print timeline
#'
#' @export

print.timeline <- function (x, ...) {
  
  n_commits <- nrow(x)
  order <- rev(seq_len(n_commits))
  
  # how much to pad the integers
  
  
  template <- "   (%i) %s\n    %s  %s [%s]\n    %s\n"
  #    (<record_id>) <message>
  #    <pipe> <datetime> [<sha>]
  #    <pipe>
  pipe <- "|"
  for (i in order) {
    
    commit <- x[i, ]
    
    msg <- gsub("\\n+", ": ", commit$message)
    sha <- substr(commit$sha, 1, 7)
    
    if (i == 1)
      pipe <- " "
    
    string <- sprintf(template,
                      commit$record_id,
                      msg,
                      pipe,
                      commit$when,
                      sha,
                      pipe)
    cat(string)
    
  }
  
}
